name: Deploy to Google Cloud Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGION: us-central1
  CLUSTER_NAME: test-cluster
  ENVIRONMENT: stage
  GCP_PROJECT_ID: previewbuild
  GAR_LOCATION: us-central1
  REPOSITORY: ryann-repo
  SERVICE: preview-build

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Get GKE credentials"
        run: |-
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }} --project ${{ env.GCP_PROJECT_ID }}

      - name: Create ConfigMap from nginx.conf
        run: |-
          kubectl create configmap nginx-config \
            --from-file=default.conf=nginx.conf \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to GKE
        run: |-
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress-http-only.yaml

      - name: Verify deployment
        run: |-
          kubectl rollout status deployment/preview-proxy --timeout=300s
          kubectl get services
          kubectl get ingress

      - name: Show deployment info
        run: |-
          echo "Deployment completed successfully!"
          echo "Service status:"
          kubectl get deployment preview-proxy
          echo "Ingress info:"
          kubectl get ingress preview-proxy-ingress-http
